---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  schedule:
    - cron: "10 2 * * 0"

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t docker-image-molecule .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-image-molecule

      - name: Verify Molecule and Ansible the built image.
        run: docker exec --tty test-container env TERM=xterm molecule --version

  # If on main branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      
      - uses: dawidd6/action-get-tag@v1
        id: tag
        with:
          # Optionally strip `v` prefix
          strip_v: true

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build and push Docker image.
        with:
          image: pincher95/${{ github.repository }}
          tags: ${{steps.tag.outputs.tag}}, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}